In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
#import data
df=pd.read_csv('bank.csv')
df.head()

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        1          1        0     2343        1     0        2   
1   56    0        1          1        0       45        0     0        2   
2   41    9        1          1        0     1270        1     0        2   
3   55    7        1          1        0     2476        1     0        2   
4   54    0        1          2        0      184        0     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    5      8      1042         1     -1         0         3        1  
1    5      8      1467         1     -1         0         3        1  
2    5      8      1389         1     -1         0         3        1  
3    5      8       579         1     -1         0         3        1  
4    5      8       673         2     -1         0         3        1

In [3]:
#check for datatypes
df.dtypes

age          int64
job          int64
marital      int64
education    int64
default      int64
balance      int64
housing      int64
loan         int64
contact      int64
day          int64
month        int64
duration     int64
campaign     int64
pdays        int64
previous     int64
poutcome     int64
deposit      int64
dtype: object

In [6]:
df['education'].unique()

array([1, 2, 0, 3], dtype=int64)

In [7]:
df['default'].unique()

array([0, 1], dtype=int64)

In [19]:
df['day'].unique()

array([ 5,  6,  7,  8,  9, 12, 13, 14, 15, 16, 19, 20, 21, 23, 26, 27, 28,
       29, 30,  2,  3,  4, 11, 17, 18, 24,  1, 10, 22, 25, 31],
      dtype=int64)

In [8]:
df['housing'].unique()

array([1, 0], dtype=int64)

In [9]:
df['contact'].unique()

array([2, 0, 1], dtype=int64)

In [11]:
df['campaign'].unique().max()

63

In [14]:
df['pdays'].unique().max()

854

In [17]:
df['previous'].unique().max()

58

In [18]:
df['previous'].unique()

array([ 0,  1,  4,  2,  3, 10,  7,  9,  5, 29,  6, 13, 17,  8, 11, 30, 22,
       58, 21, 14, 26, 12, 19, 55, 23, 15, 20, 27, 16, 41, 40, 28, 18, 37],
      dtype=int64)

In [5]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='object')

In [ ]:
#check for null values
df.isnull().sum()

In [ ]:
#visualise
sns.countplot(data=df,x='education')
f=df['education'].value_counts()
plt.yticks(f)
plt.show()

#do the same for rest of the parameters+

In [ ]:
#split input and output
X=df.drop('deposit',axis=1)
Y=df['deposit']

In [ ]:
X.head()

In [ ]:
Y.head()

In [ ]:
#train test split
from sklearn.model_selection import train_test_split
#create object of inbuilt class train_tesT_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [ ]:
#Apply scaling : standard scaler
from sklearn.preprocessing import StandardScaler
#create object of standard scaler class
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [ ]:
X_train

In [ ]:
#call decision tree classifier class--> outer class tree-->SR learn package
from sklearn.tree import DecisionTreeClassifier

In [ ]:
#create the object of class DecisionTreeClassifier
dt1=DecisionTreeClassifier(random_state=1,criterion='entropy') #use entropy classification

In [ ]:
#train model with 70% traiing data
dt1.fit(X_train,Y_train)

In [ ]:
#to test the model with 30% data
#use predict() inbuilt method
Y_pred=dt1.predict(X_test)

In [ ]:
Y_pred

In [ ]:
#create dataframe with help od dictionery
dict={"Actual output":Y_test,"predicted output":Y_pred}
df1=pd.DataFrame(dict)
df1.head(10)

In [ ]:
#to show information gain of each input features
#use inbuilt function attributes features_importance_ of decision tree class

IG=dt1.feature_importances_

col=X.columns # columns inbuilt attributes
#create a dictionery
dict={'input columns':col,'Information Gain':IG}
df2=pd.DataFrame(dict)
df2

In [ ]:
#create a tree
from sklearn import tree
features=X.columns # input features
plt.figure(figsize=(20,20))
_=tree.plot_tree(dt1,feature_names=features,filled=True)
plt.show()

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred))

In [ ]:
print (confusion_matrix(Y_test,Y_pred))

In [ ]:
#create user defined function
def create_model(model): #user defined object and create_model() user defined function
    model.fit(X_train,Y_train) #train data with 70% data
    #test the model with 30% data
    Y_pred=model.predict(X_test)
    #generate classification report of model
    print(classification_report(Y_test,Y_pred))
    #generate confusion matirx
    print(confusion_matrix(Y_test,Y_pred))
    return model

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
#perform model with help of logistic regression algorithm
from sklearn.linear_model import LogisticRegression

In [ ]:
#create object of class LogisticRegression
lr=LogisticRegression()

In [ ]:
#call function
LG=create_model(lr)

In [ ]:
#in logistic regression, got recall 77% behind the reason for less score, features are not selected automatically
#use 2nd algorithm
from sklearn.tree import DecisionTreeClassifier

In [ ]:
#perform the model with DecisionTree classifier(gini index)
dt=DecisionTreeClassifier(random_state=1)

In [ ]:
#call function
#call function and passing the object of DecisionTreeClassifier
create_model(dt)

In [ ]:
IG=dt.feature_importances_
col=X.columns
dict={'input columns':col,'IG':IG}
df1=pd.DataFrame(dict)
df1.sort_values('IG',ascending=False,ignore_index=True)

In [ ]:
#create a tree
from sklearn import tree
features=X.columns # input features
plt.figure(figsize=(40,40))
_=tree.plot_tree(dt,feature_names=features,filled=True)
plt.show()

In [ ]:
# perform the model with DecisionTree classifier
dt1=DecisionTreeClassifier(random_state=1,criterion='entropy')

In [ ]:
create_model(dt1)

In [ ]:
#But we got less score 0.77 % its good but not excellent , 
#region behind less score , overfit means 
#model is overfit so reduced the overfitting situation : - 
#then we use pruning technique 

#How to reduced a overfitting situation 
#By using the Pruning technique : -
#There are 2 types of pruning technique : -
#1. max_depth : inbulit parameter
#2. min_samples_leaf  : inbuilt parameter
#leaf means no child

#limitation oa decision tree classifier class
#1 processing time too much
#2 overfitiing occours

In [ ]:
#1. max depth : max to max =8 or less
'''for d in range(1,9):
    #create the object of decision treeclassifier class
    dt1=DecisionTreeClassifier(random_state=1,max_depth=d)
    print("Max_depth:",d)
    #callfunction for train,test and generate report
    dt1=create_model(dt1)'''

In [ ]:
#create the object of decision treeclassifier class
dt2=DecisionTreeClassifier(random_state=1,max_depth=5)
dt2=create_model(dt2)

In [ ]:
IG=dt2.feature_importances_
col=X.columns
dict={'input columns':col,'IG':IG}
df1=pd.DataFrame(dict)
df1.sort_values('IG',ascending=False,ignore_index=True)

In [ ]:
#create a tree
from sklearn import tree
features=X.columns # input features
plt.figure(figsize=(40,40))
_=tree.plot_tree(dt2,feature_names=features,filled=True)
plt.show()

In [ ]:
#21-06-2023

In [ ]:
#min_samples_leaf inbuilt parameter
#leaf : no child
#min_samples_leaf>=45 and <100

In [ ]:
#create the object of DecisionTreeClassifier class
'''for i in range(45,101):
    #create the object of decision tree classifier class and passing the value of
    #parameter min_samples_leaf
    dt2=DecisionTreeClassifier(random_state=1,min_samples_leaf=i)#bydefault gini index
    #call function for train,test split
    dt2=create_model(dt2)'''

In [ ]:
dt3=DecisionTreeClassifier(random_state=1,min_samples_leaf=45)#bydefault gini index
dt3=create_model(dt3)

In [ ]:
IG=dt3.feature_importances_ 
col=X.columns
dict={'input columns':col,'IG':IG}
df1=pd.DataFrame(dict)
df1.sort_values('IG',ascending=False,ignore_index=True)

In [ ]:
#create a tree
from sklearn import tree
features=X.columns # input features
plt.figure(figsize=(40,40))
_=tree.plot_tree(dt3,feature_names=features,filled=True)
plt.show()

In [ ]:
#note:here best method in this bank dataset
#decisionTreeClassifier with pruning Technique min_samples_Leaf=45
#got recall= 87%

In [ ]:
#ensembling Technique
#1 RandomForestTree  : work on bagging classifier
#RandomForestTree is the type of Bootstrapping
#and Bootstrapping is the type of Ensembling Technique

In [ ]:
#inbuilt class RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
#ensemble means to train the dataset from multiple algorithm
#in case of RandomForestClassifier, To train dataset from multiple decisiontree

In [ ]:
X.shape

In [ ]:
#create the object of RandomForestClassifier class
'''for i in range(1,17):
    #create the object of ranfomforestclassifier class
    rfc=RandomForestClassifier(random_state=1,max_features=i)
    #by default use algorithm DecisionTreeclassifier
    # max_features inbuilt parameters of RandomForestClassifier class
    # call function
    print('max_features:',i)
    rfc=create_model(rfc)'''

In [ ]:
# using max features =4
rfc=RandomForestClassifier(random_state=1,max_features=4)
print('max_features:',4)
rfc=create_model(rfc)

In [ ]:
IG=rfc.feature_importances_
col=X.columns
dict={'input columns':col,'IG':IG}
df1=pd.DataFrame(dict)
df1.sort_values('IG',ascending=False,ignore_index=True)

In [ ]:
#got recall=88% and accuracy =85%, RFC is best also, for bank dataset

In [ ]:
#22-06-2023

In [ ]:
#Boosting TEchnique
# 1.ADA Boost means Adaptor Boosting
# Inbuilt class AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
'''for i in range(1,17):
    #create object of AdaBoostClassifier class
    ada=AdaBoostClassifier(random_state=1,n_estimators=i)
    print("no of estimators:",i)
    #call function
    ada=create_model(ada)'''

In [ ]:
#create object of AdaBoostClassifier class
ada=AdaBoostClassifier(random_state=1,n_estimators=11)
#n_estimators means how many decision stump, decision stump depend on
#n_estimators means how many decision stump , decision stump depend on 
#no. of input in given dataset
#in case of our dataset , no. of features means inputs =13 
#call function

ada=create_model(ada)

In [ ]:
IG=ada.feature_importances_
col=X.columns
dict={'input columns':col,'IG':IG}
df1=pd.DataFrame(dict)
df1.sort_values('IG',ascending=False,ignore_index=True)

In [ ]:
#in ada boost, got recall=0.79

In [ ]:
#2. gradient Boost technuique : second tech. of Boosting Ensembling 
#technique 
# GB  : - its create a fully grown tree.this algorithm is focus on 
#short comings 
#short comings means error
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
'''for i in range(10,101):
    #create object of GradientBoostingClassifier and passing the parameter n_estimators between
    #10 to 100
    gbc=GradientBoostingClassifier(random_state=1,n_estimators=i)
    #n_estimators means how many decison tree create for train the model
    print("n_estimators means no of decisin tree =",i)
    gbc=create_model(gbc)'''

In [ ]:
#create object of GradientBoostingClassifier and passing the parameter n_estimators between
    #10 to 100
gbc=GradientBoostingClassifier(random_state=1,n_estimators=72)
gbc=create_model(gbc)

In [ ]:
IG=gbc.feature_importances_
col=X.columns
dict={'input columns':col,'IG':IG}
df1=pd.DataFrame(dict)
df1.sort_values('IG',ascending=False,ignore_index=True)

In [ ]:
#extreme Gradient Boost XGB:-

In [ ]:
#26/6/2023

In [ ]:
#XGB Boosting (26-06)
#3. Extreame Gradient Boosting  : 3rd technique of Boosting 
#This is better version of gradient boosting . . short form XGB 
#why call better version of Gradient Boosting : -
#1. XG Bossting use : - Multithreading technique(parallel processing)
#2. It takes less memory space and faster 
#3. It is very useful to handle huge amt of data .Its deal large amount of data
#4. Its handle outlier because have inbuilt capability
#5. Its handle null values 
#6. Its handle automatic overfitting situation .

In [ ]:
#pip install xgboost

In [ ]:
from xgboost import XGBClassifier

In [ ]:
'''#create an object of XGB classifier class
for i in range(1,101):
    xgc=XGBClassifier(n_estimators=100,reg_alpha=i,random_state=1)
#reg means regularisation and alpha : hypermeter alpha means lambda
        #reg_alpha is a inbuilt parameter of XGBClassifier class,it is used 
        #to handle outlier and overfitting automatically and 1 means True
    print ('No of iteration:',i)
    xgc=create_model(xgc)'''

In [ ]:
#create an object of XGB classifier class
xgc=XGBClassifier(n_estimators=100,reg_alpha=21,random_state=1)
#reg means regularisation and alpha : hypermeter alpha means lambda
        #reg_alpha is a inbuilt parameter of XGBClassifier class,it is used 
        #to handle outlier and overfitting automatically and 1 means True
#print ('No of iteration:',i)
xgc=create_model(xgc)

In [ ]:
#score in XGB : recall = 88% and accuracy=85%
#in random forest tree : recall =88% and accuracy =85%

In [ ]:
# text classification algorithm : support vector machine SVM
#there are 2 types of data :
#1. linear data    2. non-linear data


In [ ]:
#if data is in linear nature: so use linear kernel function
#but if data is non-linear nature , so use 2 types of kernel function
#1. Polynomail kernel function
#2. Radial basis kernel function

In [ ]:
#linear kernal function
from sklearn.svm import LinearSVC

In [ ]:
#create a object
svc=LinearSVC(random_state=1)  #hard margin

In [ ]:
#call function
svc=create_model(svc)

In [ ]:
#here recall=77% which is good but not better,we can more better
#may be model is overfit ,so reduced overfit situation
#means to add external error during training time means use soft margin
#means maybe data is linear but model is overfit so add external error during training time
#create object of LinearSVC class and passing extra parameter C,here C is error parameter
#whcih values between 0 to 1
svc1=LinearSVC(random_state=1,C=0.01)
svc1=create_model(svc1)

In [ ]:
from sklearn.svm import SVC

In [ ]:
poly_svc=SVC(random_state=1,kernel="poly")

In [ ]:
#call function
poly_svc=create_model(poly_svc)

In [ ]:
# create object of radiall basis function
r_svc=SVC(random_state=1,kernel="rbf")

In [ ]:
#call function
r_svc=create_model(r_svc)

In [ ]:
#conclusion=bank.csv dataset is non-linear(radial basis)
#recall=84% and accuracy =82%

In [ ]:
#to store object of model and object of standard scaler class but in binary format
#store data in file in binary format, take mode of file : wb(write binary)
#first open file in write binary
import pickle
file1=open("scale.pkl",'wb')
#syntax pickle.dump(object, temp file)
pickle.dump(ss,file1)
file1.close()

In [ ]:
file2=open("decisiontreegini.pkl",'wb')
pickle.dump(dt,file2)
file2.close()

In [ ]:
file3=open("decisiontreeentropy.pkl",'wb')
pickle.dump(dt1,file3)
file3.close()

In [ ]:
file4=open("decisiontreemaxdept.pkl",'wb')
pickle.dump(dt2,file4)
file4.close()

In [ ]:
file5=open("decisiontreeminsamples.pkl",'wb')
pickle.dump(dt3,file5)
file5.close()

In [ ]:
file6=open('Randomforest.pkl','wb')
pickle.dump(rfc,file6)
file6.close()

In [ ]:
file7=open('adaptorboost.pkl','wb')
pickle.dump(ada,file7)
file7.close()

In [ ]:
file8=open('logisticregression.pkl','wb')
pickle.dump(lr,file8)
file8.close()

In [ ]:
file9=open('gradientboost.pkl','wb')
pickle.dump(gbc,file9)
file9.close()

In [ ]:
file10=open('extremegradientboost.pkl','wb')
pickle.dump(xgc,file10)
file10.close()

In [ ]:
file11=open('supportvector','wb')
pickle.dump(r_svc,file11)
file11.close()